apiVersion: apps/v1
kind: Deployment
metadata:
  name: spectre
  labels:
    app: spectre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spectre
  template:
    metadata:
      labels:
        app: spectre
    spec:
      containers:
      - name: spectre
        image: spectre:latest
        imagePullPolicy: IfNotPresent
        command: ["spectre", "--api", "--authorized"]
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
